travis:
  secure:
    BINSTAR_TOKEN: Rq1HYwUnFItQKJfb7HamrDLMK/tM1OdSY+PQKXPtG6T1AeuljCOm/vyEjAPMPqK/HQMyQ/+H3TCNbwsk+McumA19GdZAyV36Psk2/8BMJF9YXOSRxtPmGIpFsx9FFs2P/Uey4Pe56Phh83JHBCMgSEhvSE4munNhAfcqCrS4hML3hyI9EvhUUtVvsm015Iv+v7z7K1I4sK0qV+hkhFxCiUOOETMKODb+wy8zXFV3rCnyTIjYzDB1xR6nwHCEnutQIFbwE3vloQnVhLlQTsyWq7BEXubyZkDeh6/jWhJ2YLQPp5G0844CbcMEp607N6c6uKVju5IJKdx/HiOxkjtqweSM3AVRoSr58kuDbtjF8imcSym5z/Y/LLQ2Z8Hdjc/XjY8Ppa91Xi9+04i0WCNcaPC0/3/7vW8hpBcqQSBbNlSEOwWVzlBeREefFscwmAILUqZdQGU6BTh6y0DGTU8jmmgiKA9cCE9VcQFf9Ob6E2RBiQ2Ee3Ih2inGnYpJFfc5zG/pV9KFrJjh57fd8vBCyLgdyCtHXWlirmxwqOnK0rnP9yCYUGMg4h3c2EVBkIYSLLdlkH7sKPq9jXYV1ZkFwmmom6TNty3MgKAx5hh3miRV0LyA2bV86+bAR4UltA+bNvF1VcCuPkDo6Kr+rRmqwziwYwYVyTZP4Jn28hqQg60=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
